title: "Vahid Moghani"
description: "Personal website of Vahid Moghani, postdoctoral researcher in health economics."
theme: minima
lang: en

markdown: kramdown

header_pages:
  - index.md
  - research.md
  - software.md
  - contact.md
