title: "Vahid Moghani"
description: "Personal webpage for Vahid Moghani"
author: "Vahid Moghani"

# Use a more visually striking GitHub Pages theme.  The "jekyll‑theme‑cayman" theme
# provides a clean layout with bold accent colours that work well for an
# academic portfolio site.  GitHub Pages will automatically pull and build
# the theme based on this setting.
remote_theme: pages-themes/time-machine@v0.2.0

plugins:
- jekyll-remote-theme

markdown: kramdown

# Expose pages in the header navigation. These paths correspond to the main
# sections of the site and will appear in order.
header_pages:
  - index.md
  - research.md
  - book-a-meeting.md
  - contact.md
  # Farsi pages can be added to the header if desired by uncommenting the lines
  #- fa/تحقیقات-آکادمیک.md
  #- fa/دیدگاه‌ها.md
  #- fa/علی-مغانی.md
