# _config.yml — using the remote “Minimal” theme

title: "Vahid Moghani"
description: "Personal webpage for Vahid Moghani"
author: "Vahid Moghani"

# Use the GitHub Pages remote “Minimal” theme
remote_theme: "pages-themes/minimal@v0.2.0"

# Enable the remote-theme plugin
plugins:
  - jekyll-remote-theme

# Markdown processor
markdown: kramdown

# Navigation is now driven by _data/navigation.yml (remove header_pages)
# Create a file at _data/navigation.yml with entries like:
#
#   - title: Home
#     url: /
#   - title: Research
#     url: /research/
#   - title: Book a Meeting
#     url: /book-a-meeting/
#   - title: Contact
#     url: /contact/
#
# That will populate your header links in the Minimal theme.
